title: "Mike’s Home Lab"
description: "Proxmox • OPNsense • VLANs • DNS • VPN • Monitoring"
theme: minima

url: "https://YOUR_GITHUB_USERNAME.github.io"
baseurl: "/homelab"

author:
  name: "Mike Anthony Molinar"

minima:
  social_links:
    - { platform: github,  user_url: "https://github.com/YOUR_GITHUB_USERNAME" }
    - { platform: linkedin, user_url: "https://www.linkedin.com/in/mike-molinar-407403186/" }

header_pages:
  - projects.md
  - architecture.md
  - runbooks.md
  - about.md
